RSWP_MVC/RSWP_UI/Controllers/RTIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RSWP_UI.Controllers
{
    public class RTIController : Controller
    {
        // GET: RTI
        public ActionResult RightToInfo()
        {
            return View();
        }

        public ActionResult StatementUnderSec()
        {
            return View();
        }

        public ActionResult StatusRTIApplication()
        {
            return View();
        }
    }
}

RSWP_MVC/RSWP_UI/Views/RTI/Partial/RTILeftMenu.cshtml
<div class="col-md-3">
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.Main</h4>
        <ul class="sideBarList">
            <li><a href="#" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.RTIActs</a></li>
            <li><a href="#" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.InformationBooklet</a></li>
            <li><a href="#" class="active" data-section="Debates" data-subsection="Important Links" data-module="Official Debate Portal">@RSWP_UI.Resources.Resource.Guide</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.RTIOnline</h4>
        <ul class="sideBarList">
            <li><a href="@Url.Action("StatusRTIApplication","RTI")" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.RTIOnline</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.RTImis</h4>
        <ul class="sideBarList">
            <li><a href="@Url.Action("StatusRTIApplication","RTI")" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.RTImis</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.Notifications</h4>
        <ul class="sideBarList">
            <li><a href="#" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.Notifications</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.Rules</h4>
        <ul class="sideBarList">
            <li><a href="#" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.Rules</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.StatementunderSec</h4>
        <ul class="sideBarList">
            <li><a href="@Url.Action("StatementUnderSec","RTI")" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.StatementunderSec</a></li>
        </ul>
    </div>
    <div class="sectionBox">
        <h4>@RSWP_UI.Resources.Resource.StatusofRTIApplication</h4>
        <ul class="sideBarList">
            <li><a href="@Url.Action("StatusRTIApplication","RTI")" class="active" data-section="Debates" data-subsection="Important Links" data-module="Verbatim Debates">@RSWP_UI.Resources.Resource.StatusofRTIApplication</a></li>
        </ul>
    </div>

</div>

RSWP_MVC/RSWP_UI/Views/RTI/Partial/_StatementUnderGrid.cshtml
    <div class="searchResulltTabl">
        <table id="member_table" class="table table-striped">
            <thead>
                <tr>
                    <th>@RSWP_UI.Resources.Resource.Year</th>
                    <th>@RSWP_UI.Resources.Resource.StatementsPDF</th>
                </tr>
            </thead>
            <tbody id="memberList">
            </tbody>
        </table>
    </div>

RSWP_MVC/RSWP_UI/Views/RTI/Partial/_StatusRTIApplicationGrid.cshtml
<div class="searchResulltTabl">
    <table id="member_table" class="table table-striped">
        <thead>
            <tr>
                <th>@RSWP_UI.Resources.Resource.Name</th>
                <th>@RSWP_UI.Resources.Resource.Designation</th>
                <th>@RSWP_UI.Resources.Resource.Address</th>
                <th>@RSWP_UI.Resources.Resource.TelNo</th>
                <th>@RSWP_UI.Resources.Resource.EMail</th>
            </tr>
        </thead>
        <tbody id="memberList">
        </tbody>

    </table>
</div>

<div class="searchResulltTabl">
    <table id="member_table" class="table table-striped">
        <thead>
            <tr>
                <th>@RSWP_UI.Resources.Resource.Name</th>
                <th>@RSWP_UI.Resources.Resource.Designation</th>
                <th>@RSWP_UI.Resources.Resource.Address</th>
                <th>@RSWP_UI.Resources.Resource.TelNo</th>
                <th>@RSWP_UI.Resources.Resource.EMail</th>
            </tr>
        </thead>
        <tbody id="memberList">
        </tbody>

    </table>
</div>

<div class="searchResulltTabl">
    <table id="member_table" class="table table-striped">
        <thead>
            <tr>
                <th>@RSWP_UI.Resources.Resource.Name</th>
                <th>@RSWP_UI.Resources.Resource.Designation</th>
                <th>@RSWP_UI.Resources.Resource.Address</th>
                <th>@RSWP_UI.Resources.Resource.TelNo</th>
                <th>@RSWP_UI.Resources.Resource.EMail</th>
            </tr>
        </thead>
        <tbody id="memberList">
        </tbody>

    </table>
</div>